<?php
/**
 * 1997-2016 Quadra Informatique
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0) that is available
 * through the world-wide-web at this URL: http://www.opensource.org/licenses/OSL-3.0
 * If you are unable to obtain it through the world-wide-web, please send an email
 * to modules@quadra-informatique.fr so we can send you a copy immediately.
 *
 * @author Quadra Informatique
 * @copyright 1997-2016 Quadra Informatique
 * @license http://www.opensource.org/licenses/OSL-3.0 Open Software License (OSL 3.0)
 */
?>
<?php $_code = $this->getMethodCode() ?>
<div class="form-list" style="display: inline-block">
    <img style="float: left" src="<?php echo $this->getSkinUrl('images/media/cybermut/cb.gif') ?>" alt="CB" />
    <img style="float: left" src="<?php echo $this->getSkinUrl('images/media/cybermut/master.gif') ?>" alt="Mastercard" />
    <img style="float: left" src="<?php echo $this->getSkinUrl('images/media/cybermut/visa.gif') ?>" alt="Visa" />
</div>

<ul class="form-list" id="payment_form_<?php echo $_code ?>" style="display:none;">
    <?php if ($_code == 'cybermut_several'): ?>
    <li class="control">
        <input type="checkbox" name="cybermut[several_implements]" id="<?php echo $_code ?>_several_implements" value="<?php echo Mage::getStoreConfig('payment/cybermut_several/terms') ?>" title="<?php echo $this->__('Payment %s times', Mage::getStoreConfig('payment/cybermut_several/terms')) ?>" class="checkbox" />
        <label for="<?php echo $_code ?>_several_implements"><?php echo $this->__('Payment %s times', Mage::getStoreConfig('payment/cybermut_several/terms')) ?></label>
        <input type="hidden" id="<?php echo $_code ?>_nbrech" name="payment[nbrech]" value="1" />
        <script type="text/javascript">
        //<![CDATA[
            var NTChecked<?php echo $_code ?> = function() {
                var elm = $('<?php echo $_code ?>_several_implements');
                if (elm.checked) {
                    $('<?php echo $_code ?>_nbrech').value = elm.value;
                } else {
                    $('<?php echo $_code ?>_nbrech').value = 1;
                }
            };

            Event.observe($('<?php echo $_code ?>_several_implements'), 'click', NTChecked<?php echo $_code ?>);
            NTChecked<?php echo $_code ?>();
        //]]>
        </script>
    </li>
    <?php endif; ?>
    <li>
        <?php echo $this->__('You will be redirected to Cybermut website when you place an order.') ?>
    </li>
</ul>