<?php
/**
 * 1997-2015 Quadra Informatique
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0) that is available
 * through the world-wide-web at this URL: http://www.opensource.org/licenses/OSL-3.0
 * If you are unable to obtain it through the world-wide-web, please send an email
 * to modules@quadra-informatique.fr so we can send you a copy immediately.
 *
 * @author Quadra Informatique <modules@quadra-informatique.fr>
 * @copyright 1997-2015 Quadra Informatique
 * @license http://www.opensource.org/licenses/OSL-3.0 Open Software License (OSL 3.0)
 */
?>

<img src="<?php echo $this->getSkinUrl('images/media/cybermut/cb.gif') ?>" alt="CB" />
<img src="<?php echo $this->getSkinUrl('images/media/cybermut/master.gif') ?>" alt="Mastercard" />
<img src="<?php echo $this->getSkinUrl('images/media/cybermut/visa.gif') ?>" alt="Visa" />
<br /><br />

<fieldset class="form-list">
    <?php $_code = $this->getMethodCode() ?>
    <ul id="payment_form_<?php echo $_code ?>" style="display:none">
        <?php if (Mage::getStoreConfig('payment/cybermut_payment/several_times_payment')): ?>
            <li class="control">
                <input type="checkbox" name="cybermut[several_implements]" id="cybermut:several_implements" value="<?php echo Mage::getStoreConfig('payment/cybermut_payment/terms') ?>" title="<?php echo $this->__('Payment %s times', Mage::getStoreConfig('payment/cybermut_payment/terms')) ?>" class="checkbox" onclick="setNbrech()" />
                <label for="cybermut:several_implements"><?php echo $this->__('Payment %s times', Mage::getStoreConfig('payment/cybermut_payment/terms')) ?></label>
                <input type="hidden" id="payment:nbrech" name="payment[nbrech]" value="1" />
            </li>
            <script type="text/javascript">
                //<![CDATA[
                function setNbrech() {
                    if ($('cybermut:several_implements').checked)
                        $('payment:nbrech').value = $('cybermut:several_implements').value;
                    else
                        $('payment:nbrech').value = 1;
                }
                //]]>
            </script>
        <?php endif; ?>
        <li>
            <?php echo $this->__('You will be redirected to Cybermut website when you place an order.') ?>
        </li>
    </ul>
</fieldset>